env:
  SEED: 42
  CUDA_DEVICE_ORDER: "PCI_BUS_ID" 
  OMP_NUM_THREADS: "4"
  CUDA_VISIBLE_DEVICES: "0"
  TRANSFORMERS_CACHE: /home/data/hf_cache/

paths:
  data_dir: "data/"
  log_dir: "artifacts/logs/"
  checkpoint_dir: "artifacts/checkpoints/"
  results_dir: "artifacts/results/"

model:
  path: "/home/llm_compression/LLaMA/Llama-2-7b-hf"
  seqlen: 2048

dataset:
  name: wikitext2

pruning:
  backend: null #cutlass cusparselt